### PR TITLE
Added a workspace sidebar to be a darker shade of normal sidebar #16

### PR DESCRIPTION
**Pull request by Jc7j**
Hi happy hacktoberfest! I've gone ahead and added a new WorkspaceSideBar.js component. I've also created a styles folder that contains styling for each component. This will help avoid styling inside of the components and let it happen in a separate file. 

I didnt add any icons or really dig deep into a good color combo, so I've just left some texts. Thanks for letting me help out!

### CODE REVIEW

**Comment by Jc7j** [comment]
@yisselda

**Comment by Jc7j** [comment]
@yutingcxiang It seems like someone else added a className of pageContainer. I've implemented my className with a css styling in a different folder (Having workspace & sidebar side-by-side + coloring). Im not sure which one you'd guys would want.

**Comment by yutingcxiang** [comment]
@Jc7j Let's use a className of page-container. As for the stylesheets, we are using sass so please update your files to be .scss and integrate them with the existing stylesheets. Thanks!

**Comment by Jc7j** [comment]
@yutingcxiang Awesome Ill get on that!

**Comment by Jc7j** [comment]
@yutingcxiang Merge changes resolved and updated it to scss!

**Comment by yisselda** [comment]
@Jc7j The tests don't pass and I saw a lot of files were deleted. Any reason for that?

Also, we want the component to dynamically change depending on its color prop.
For example, if the color is dark purple, then the left part is dark purple and the right part is a lighter shade. Then if we change the color prop to dark blue, we want the component to refresh with the dark blue on the left side and a lighter blue on the right side of the sidebar.

https://stackoverflow.com/questions/5560248/programmatically-lighten-or-darken-a-hex-color-or-rgb-and-blend-colors

**Pull request closed without merging**
