### PR TITLE
Issue 25 Add storybook

### LINKED ISSUE #25: Add Storybook for component preview & style guide?
Or some other equivalent. 

https://storybook.js.org/
https://github.com/styleguidist/react-styleguidist

### PR DESCRIPTION
**Pull request by tvandort**
Fixes #25 

Adds [Storybook](https://storybook.js.org/) for component preview & maybe style guide?

### CODE REVIEW

**Comment by yisselda** [comment]
@tvandort Looks good thanks! I tried rebasing and got an error about an `at-rule` in a style file. It seems like an issue with the `@import`. Do you have an idea how to solve it? Maybe a webpack config that needs to be tunned?
https://github.com/yisselda/SlackableThemes/blob/4cc78d38414e40d465717b9cee8e2a33eb0427fa/src/styles/sidebar.scss

**Comment by yisselda** [comment]
Screen Shot 2019-10-07 at 11 26 53 PM

**Comment by tvandort** [comment]
Should be working now. Had to add a webpack config for storybook to load scss. I also took the opportunity to shuffle things about originally I had the stories living next to the source file that they represented but given the `styles` and `tests` folders it seemed more natural to have a `stories` folder as well.

**Comment by yisselda** [comment]
@tvandort Thanks! 💯

**Pull request merged**
